apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-gitops1
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/ArgoCD101-GuestbookGitOps/
    repoURL: https://github.com/ppapasani1/ArgoCDRollouts
